ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      DOUBLE PRECISION G
      COMMON/STRONG/ G

      DOUBLE COMPLEX GAL(2)
      COMMON/WEAK/ GAL

      DOUBLE PRECISION MU_R
      COMMON/RSCALE/ MU_R

      DOUBLE PRECISION NF
      PARAMETER(NF=0)

      DOUBLE PRECISION MDL_MS,MDL_MU,MDL_MT,MDL_MW,MDL_MDVB,MDL_MZ
     $ ,MDL_MXD,MDL_MTA,MDL_MC,MDL_MB,MDL_ME,MDL_MD,MDL_MH,MDL_MMU

      COMMON/MASSES/ MDL_MS,MDL_MU,MDL_MT,MDL_MW,MDL_MDVB,MDL_MZ
     $ ,MDL_MXD,MDL_MTA,MDL_MC,MDL_MB,MDL_ME,MDL_MD,MDL_MH,MDL_MMU


      DOUBLE PRECISION MDL_WZ,MDL_WH,MDL_WW,MDL_WDVB,MDL_WT

      COMMON/WIDTHS/ MDL_WZ,MDL_WH,MDL_WW,MDL_WDVB,MDL_WT


      DOUBLE COMPLEX GC_15

      COMMON/COUPLINGS/ GC_15

