(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



(* ::Input::Initialization:: *)
SetDirectory[Directory[]];
$spectruminputfile="spectruminput.mx";
$outputfolder="scanfiles";
If[DirectoryQ[$outputfolder]==False,CreateDirectory[$outputfolder]];
(*fixedform is what makes the numbers nice to print to a file*)
StringPadLeft["",1];(*this must be evaluated first for no evident reason*)fixedform[numd_,data_]:=Module[{ef},ef[s_String/;StringTake[s,1]=="-"]:="-"<>StringPadLeft[StringTake[s,{2,-1}],2,"0"];
ef[s_String]:="+"<>StringPadLeft[s,2,"0"];
NumberForm[data,{numd,numd},ExponentFunction->(#&),NumberSigns->{"-"," "},NumberFormat:>(Row[{StringPadRight[#1,numd+2,"0"],"E",ef[#3]}]&)]]

parameterslarge={{"mxd",3 10.^4,10.^6,40},{"gsm",10.^-9,10.^-7.5,40},{"adm"},{"mdvb"}};


parameters[i_]:=(logstep=(Log10[parameterslarge[[2,3]]]-Log10[parameterslarge[[2,2]]])/(parameterslarge[[2,4]]-1);
{parameterslarge[[1]],{parameterslarge[[2,1]],10^(Log10[parameterslarge[[2,2]]]+(i-1)*logstep),10^(Log10[parameterslarge[[2,2]]]+(i-1)*logstep),Null},parameterslarge[[3]],parameterslarge[[4]]})
parameters[5]


(* ::Input::Initialization:: *)
Do[If[FileExistsQ[$spectruminputfile],DeleteFile[$spectruminputfile]];
Export[$spectruminputfile,parameters[i]];
Run["math -run -noprompt < spectrum.m"];
m\[Chi]scan=Import["eflux0","TSV"];
Export[$outputfolder<>"/"<>ToString[i]<>"mxscan.mx",m\[Chi]scan];
,{i,1,parameterslarge[[2,4]]}]
