(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



(* ::Input::Initialization:: *)
SetDirectory[NotebookDirectory[]];

$spectruminputfile="spectruminput.mx";

nevents=10000; (*number of events per mg5 run*)
parameters=Import[$spectruminputfile]
(*parameters={{"mxd",10.^5,10.^5,Null},{"gsm",4 10.^-11,4 10.^-11,Null},{"adm"},{"mdvb"}}*)
(*parameters to be tracked. First two have syntax {"name", scan start, scan end, number of steps}. To not scan set start = end and steps = Null*)
intab=Table[{10.^par1,10.^par2,0.035 10.^par1/1000.,0.5},{par1,Log10[parameters[[1,2]]],Log10[parameters[[1,3]]],If[parameters[[1,2]]!=parameters[[1,3]],(Log10[parameters[[1,3]]]-Log10[parameters[[1,2]]])/(parameters[[1,4]]-1.),Null]},{par2,Log10[parameters[[2,2]]],Log10[parameters[[2,3]]],If[parameters[[2,2]]!=parameters[[2,3]],(Log10[parameters[[2,3]]]-Log10[parameters[[2,2]]])/(parameters[[2,4]]-1.),Null]}];
If[Length[Dimensions[intab]]==3,
intab=Flatten[intab,1]](*intab is the table of parameters to be input into madgraph for the scan.*);

(*fixedform is what makes the numbers nice to print to a file*)
StringPadLeft["",1];(*this must be evaluated first for no evident reason*)fixedform[numd_,data_]:=Module[{ef},ef[s_String/;StringTake[s,1]=="-"]:="-"<>StringPadLeft[StringTake[s,{2,-1}],2,"0"];
ef[s_String]:="+"<>StringPadLeft[s,2,"0"];
NumberForm[data,{numd,numd},ExponentFunction->(#&),NumberSigns->{"-"," "},NumberFormat:>(Row[{StringPadRight[#1,numd+2,"0"],"E",ef[#3]}]&)]]

hawc={{0.5,2.2 10^-12},{1.6,8.8 10^-13},{5.0,2.8 10^-13},{15.7,8.1 10^-14},{50,6.3 10^-14}};
(*TeV / cm^2 / s for each bin, first number in element is left side of bin*)
(*Do[*)
$mg5outputfile = "dvb";
$inputfile="anninput";
$mg5runfile="mg5run";
$pythiaoutputfile="pythiaoutput";
$pythonoutputfile="photonenergy";
$resultsfile="eflux"<>ToString[$KernelID];
$debugfile = "debug"<>$mg5outputfile;
build=0;
talpha="thermal";
au=1.49598 10^11 *100;(*distance from earth to sun in cm*)
aum=1.49598 10^11 ;(*distance from earth to sun in m*)
SR=6.957 10^8;(*Solar radius in m*)
If[FileExistsQ[$debugfile],DeleteFile[$debugfile]];


(* ::Input::Initialization:: *)
If[FileExistsQ["pythia8_card_"<>$mg5outputfile<>".dat"],DeleteFile["pythia8_card_"<>$mg5outputfile<>".dat"]];
CopyFile["pythia8_card_default.dat","pythia8_card_"<>$mg5outputfile<>".dat"];
pythiacard=OpenAppend["pythia8_card_"<>$mg5outputfile<>".dat",PageWidth-> 500];
WriteString[pythiacard,"ResonanceWidths:minWidth = 1e-30"];(*This enables particles with very small widths to still decay by avoiding their width being set to zero for being below the default min of 1e-20*);
Close[pythiacard];


(* ::Input::Initialization:: *)
(*intab=Table[{lmx,lma},{lmx,lm\[Chi]start,lm\[Chi]end,lm\[Chi]step},{lma,lmAstart,lmAend,lmAstep}];*)

(*ScanMadgraph requires a list of tuples containing {lm\[Chi],lmA} in each entry, generated above by intab*)
ScanMadgraph[partable_]:=(
If[FileExistsQ[$mg5runfile],DeleteFile[$mg5runfile]];
If[DirectoryQ[$mg5outputfile],DeleteDirectory[$mg5outputfile,DeleteContents->True]];
mg5run={"import model ./SMDP_UFO/",
 "set automatic_html_opening False",
 "generate ~xd ~xd~ > dvb dvb",
"output " <> $mg5outputfile,
"launch "<>$mg5outputfile,
"shower = Pythia8",
"set nevents "<>ToString[nevents],
"set WDVB Auto",
"set ptj 0.0",
"set pta 0.0",
"set ptl 0.0",
"set etaj -1.0",
"set etaa -1.0",
"set etal -1.0",
"./pythia8_card_"<>$mg5outputfile<>".dat\n"};
Export[$mg5runfile,mg5run,"text"];
runfile=OpenAppend[$mg5runfile,PageWidth-> 500];
(*tab=Flatten[partable,1];*)
Do[
WriteString[runfile,"set " <>parameters[[1,1]]<>" "<> ToString[fixedform[6,partable[[i,1]]]]<>"\n"];
WriteString[runfile,"set "<>parameters[[2,1]]<>" "<>ToString[fixedform[6,partable[[i,2]]]]<>"\n"];
WriteString[runfile,"set "<>parameters[[3,1]]<>" " <> ToString[fixedform[6,partable[[i,3]]]]<>"\n"];
WriteString[runfile,"set "<>parameters[[4,1]]<>" " <> ToString[fixedform[6,partable[[i,4]]]]<>"\n"];
WriteString[runfile,"set ebeam1 "<>ToString[fixedform[6,partable[[i,1]]*1.00001]]<>"\n"];
WriteString[runfile,"set ebeam2 "<>ToString[fixedform[6,partable[[i,1]]*1.00001]]<>"\n"];
WriteString[runfile,"set WDVB Auto\n"];
If[i!=Length[partable],WriteString[runfile,"launch "<>$mg5outputfile<>"\n"]];
,{i,Length[partable]}];
Close[runfile];
Run["mg5_aMC "<>$mg5runfile];)
(*ScanMadgraph[intab]*)


(* ::Input::Initialization:: *)
readparameter[path_,name_]:=(fno=OpenRead[path];
SetStreamPosition[fno,0];
fnf=Find[fno,"# "<>name];
str=StringTake[fnf,{StringPosition[fnf," # "<>name][[1,1]]-12,StringPosition[fnf," # "<>name][[1,1]]-1}];
par=ToExpression[StringReplace[str,{"e+"-> "*10^","e-"-> "*10^-"}]];
Close[fno];
par
)

readallparameters[path_]:=(
Table[readparameter[path,parameters[[i,1]]],{i,1,Length[parameters]}])
(*readallparameters[fnb[[1]]]*)

readwidth[path_,PDG_]:=(fno=OpenRead[path];
SetStreamPosition[fno,0];
fnf=Find[fno,"DECAY "<>" "<>PDG];
str=StringTake[fnf,{StringPosition[fnf,PDG][[1,2]]+4,StringPosition[fnf,PDG][[1,2]]+15}];
width=ToExpression[StringReplace[str,{"e+"-> "*10^","e-"-> "*10^-"}]];
Close[fno];
width
)
(*readwidth["dvb/Events/run_01/run_01_tag_1_banner.txt","100001"]*)


(* ::Input::Initialization:: *)
(*pythiaread[] for all run folders in the mg5outputfile reads all the specified parameters from the banners, then decompresses the pythia events. The python file read.py then reads the pythia files, and extracts the photon energy spectrum, which is appended to the results file *)
pythiaread[]:=
(fn=FileNames[All,$mg5outputfile<>"/Events"];
fnb=fn;
Do[
fnb[[fni]]=fn[[fni]]<>"/"<>StringTake[fn[[fni]],{StringPosition[fn[[fni]],"run_"][[1,1]],StringLength[fn[[fni]]]}]<>"_tag_1_banner.txt",{fni,1,Length[fn]}];
(*fnb is the file name of the banner for run_fni*)
Do[fno=OpenRead[fnb[[fni]]];
m\[Chi]read=readparameter[fnb[[fni]],"mxd"];
mAread=readparameter[fnb[[fni]],"mdvb"];
admread=readparameter[fnb[[fni]],"adm"];
gsmread=readparameter[fnb[[fni]],"gsm"];
widthread=readwidth[fnb[[fni]],"100001"];
If[FileExistsQ[$pythiaoutputfile<>ToString[fni]],DeleteFile[$pythiaoutputfile<>ToString[fni]]];
Run["gzip -d < "<>fn[[fni]]<>"/tag_1_pythia8_events.hepmc.gz > ./"<>$pythiaoutputfile<>ToString[fni]];
If[FileExistsQ[$pythonoutputfile<>ToString[fni]],DeleteFile[$pythonoutputfile<>ToString[fni]]];
Run["python read.py "<>$pythiaoutputfile<>ToString[fni]<>" "<>$pythonoutputfile<>ToString[fni]];
DeleteFile[$pythiaoutputfile<>ToString[fni]];
photonE=Flatten[Import[$pythonoutputfile<>ToString[fni]]];
(*Print[{m\[Chi]read,mAread,admread,gsmread,photonE}];*)
If[FileExistsQ[$inputfile],DeleteFile[$inputfile]];
input={"build "<>ToString[build],
"mx "<>ToString[fixedform[6,m\[Chi]read]],
"mA "<>ToString[fixedform[6,mAread]],
"talpha "<>ToString[fixedform[6,admread]],
"gsm "<>ToString[fixedform[6,gsmread]](*If[StringMatchQ[ToString[talpha],"thermal"],talpha,ToString[fixedform[6,talpha]]]*)};
Export[$inputfile,input,"text"];
Run["math -run -noprompt < annrate.m"];
annin=Import["ann","Table"]//ToExpression;
annrate=annin[[1,1]](*DM annihilation rate per second*);
sigmacm=annin[[2,1]](*DD \[Sigma] in cm^2*);
taurat=annin[[3,1]](*ratio of equilibrium time over lifetime of sun*);
\[Tau]=\[HBar]/(widthread (*GeV*) (10^9)(*eV/GeV*) )/.{\[HBar]-> 4.135667662 10^-15(*eV s*)};
\[Gamma]=m\[Chi]read/mAread;
vel=c Sqrt[1-1/\[Gamma]^2]/.{c-> 3 10^8(*m/s*)};
Pr[d_]:=Exp[-d/( vel \[Gamma] \[Tau] )](*Probability it has survived by distance d*);
Prdetect=Pr[SR]-Pr[aum](*How many decay between the surface of the sun and the distance to earth*);
eflux=Table[photonE[[i]]/nevents*annrate 1/(4\[Pi] au^2) Prdetect,{i,1,Length[photonE]}];
outlist={m\[Chi]read,mAread,admread,gsmread,annrate,eflux,sigmacm,taurat,widthread};
Print[outlist];
results=OpenAppend[$resultsfile,PageWidth-> 500];
Write[results,outlist];
Close[results];
(*DeleteFile[$pythiaoutputfile<>ToString[fni]];*)
DeleteFile[$pythonoutputfile<>ToString[fni]];
If[admread>1,(Print["Warning: Dark photon - DM fine structure constant of ",admread," exceeding perturbativity"];
(*Warning outputs*)
dbo=OpenAppend[$debugfile,PageWidth-> 1000];
Write[dbo,"adm > 1: "];
Write[dbo,outlist];
Close[dbo];)];
If[taurat>1,(Print["Warning: Equilibrium time greater than sun lifetime, ratio is: ",taurat];
(*Warning outputs*)
dbo=OpenAppend[$debugfile,PageWidth-> 1000];
Write[dbo,"tauratio > 1: "];
Write[dbo,outlist];
Close[dbo];)];
,{fni,1,Length[fn]}])
(*pythiaread[]*)


(* ::Input::Initialization:: *)
(*This section actually performs the scan; it will generate 10 madgraphs at a time, then read them and delete them, to avoid filling up the computer storage*)
finalscan[]:=(
If[FileExistsQ[$resultsfile],DeleteFile[$resultsfile]];
lefttab=intab;
Do[If[Length[lefttab]>10,
scantab=Take[lefttab,10];
lefttab=Drop[lefttab,10];,
scantab=lefttab];
ScanMadgraph[scantab];
pythiaread[];
,{i,1,Length[intab],10}]
)
finalscan[]



